services:
  - type: web
    name: zooscan-server
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npx tsx src/app.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
